sonar.projectKey=autoclick
sonar.projectName=autoclick
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=.
sonar.test.inclusions=**/*.test.js,**/*.test.ts,**/*.test.tsx,**/*.spec.js,**/*.spec.ts,**/*.spec.tsx

sonar.exclusions=**/node_modules/**,**/.next/**,**/coverage/**,**/public/**,**/*.config.js,**/*.config.cjs,**/*.config.ts,**/*.config.mjs

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPaths=tsconfig.json